### ISSUE TITLE
Uploading images with spaces in filename generates TCPDF error upon PDF export

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#10]
How to reproduce:
1) Create a Grid view
2) Create a field type "Picture"
3) Create a PDF view
4) Add an entry and upload an image that has spaces in the filename (uploading files with without spaces in filenames works fine)
5) Export PDF

Result:

Exception - TCPDF ERROR: [Image] Unable to get the size of the image: http://localhost/moodle/pluginfile.php/13472/mod_datalynx/content/409/Screenshot_2018-09-19%20H%C3%9C4%20SPO%201%20%2C%203%204%20Fall%20%28servus%2C%20miles%2C%20puella%3B%20Sg%20Pl%29.png

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:
```

    line 2927 of /lib/tcpdf/tcpdf.php: Exception thrown
    line 6890 of /lib/tcpdf/tcpdf.php: call to TCPDF->Error()
    line 18897 of /lib/tcpdf/tcpdf.php: call to TCPDF->Image()
    line 18284 of /lib/tcpdf/tcpdf.php: call to TCPDF->openHTMLTagHandler()
    line 5828 of /lib/tcpdf/tcpdf.php: call to TCPDF->writeHTML()
    line 18216 of /lib/tcpdf/tcpdf.php: call to TCPDF->MultiCell()
    line 741 of /mod/datalynx/view/pdf/view_class.php: call to TCPDF->writeHTML()
    line 251 of /mod/datalynx/view/pdf/view_class.php: call to datalynxview_pdf->write_html()
    line 138 of /mod/datalynx/view/pdf/view_class.php: call to datalynxview_pdf->process_export()
    line 672 of /mod/datalynx/mod_class.php: call to datalynxview_pdf->process_data()
    line 50 of /mod/datalynx/view.php: call to datalynx->set_content()
```

**Comment by michaelpollak** [comment]
Good morning David,
I have tested your report as suggested and found that spaces in filenames are no problem here. I also checked if the specific filename is a problem and renamed one of my files 
**Screenshot_2018-09-19 HÜ4 SPO 1 , 3 4 Fall (servus, miles, puella; Sg Pl).png**

I was able to upload and export this to pdf as well.  Can you send the specific file, maybe it is just corrupted?

Tested this behaviour with mdl 3.4 and 3.5 just to be sure.

**Comment by michaelpollak** [comment]
Yes, type picture and it shows up in the exported pdf as picture. Maybe some more settings I missed or a corrupted file?

**Comment by dasistwas** [comment]
Please test with the course I sent to you via email. I tested on 2 different systems, the same error. So I think it is not possible you do not get an error.

**Comment by dasistwas** [comment]
Special characters also do work?

**Comment by michaelpollak** [comment]
Was too focused on spaces, you are right. Fixed this in the commit this morning.

For future reference:
We look for a specific file in the database by its hash value. The hashvalue moodle builds is based on the files path. When moodle creates this value the url is just parsed as is, with all special characters in place. When we try to find this file we also create a sha1 hash but we do so with the encoded path variable. This gives a potentially wrong hash and so does not find any file, leads to an error.

I tried to find out why it does work with my minimal example. Replace tags is not even invoked but the image still is parsed in the pdf ultimately, despite spaces. Curious but the fix is the proper behavior and works with a lot of weird filenames (normal ones too).

**Comment by dasistwas** [comment]
OK, this is fixed for images. When including Files (which does not make any sense anyway) a non valid temp link is included. So maybe in the future we are going to address that problem. For now I close this issue. Thank you for fixing the problem.
