### ISSUE TITLE
Error adding fields in csv view

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#117]
When trying to enter fields in the csv view, when clicking on field tag, the tag is not included, I have to write it manually.

Attached screenshots.
I have already sent the backup.

Thanks for your great work!

![cap-10](https://user-images.githubusercontent.com/61394948/77094072-3e900880-6a0c-11ea-9d58-a246ee9dac58.png)
![cap-11](https://user-images.githubusercontent.com/61394948/77094082-42238f80-6a0c-11ea-8d5e-b9e7c20b4297.png)

**Comment by michaelpollak** [comment]
So my proposed solution to this issue is to remove the select menu. CSV export is implemented with a textarea - as opposed to the editor our field tag dropdown selector is programmed for. Default view throws all fields into the view and users can remove or add fields by typing them in. 
Users working with the CSV feature are probably powerusers and thus know what fields exist and what they want to export.
I removed the non-functional tag selector and added a help button to explain the feature.

**Comment by jesusman111** [comment]
Ok.
Thank you so much for everything

**Comment by dasistwas** [comment]
A list of selectable fields would be nice. That's quite radical ḿove to delete the selector. Nevertheless I will close this issue.

**Comment by jesusman111** [comment]
I think that while field functionality is fixed, it is best to display it.
Could it be left as it was? (show field).
Thank you
