### ISSUE TITLE
Files uploaded in fieldgroup file field are not saved

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#20]
This happens only when I have more than one entry per user. The first entry of the user is correctly saved, the second is not saved.

How to reproduce:

1) Add a field of type file
2) Add fieldgroup field including the file field
3) add an entry and upload a file for each file field in the fieldgroup
4) Save entry and display
5) Result: No files are displayed.

Attention: All fields are affected. Not only files. If a user has 2 entries, then only the data is only saved for the first entry!

**Comment by michaelpollak** [comment]
Can't reproduce this (yet), files are shown as expected after upload.
Also I can save multiple entries with the same userid without problems.

Will test with different users and roles just to make sure, thank you for your feedback.

**Comment by michaelpollak** [comment]
Thank you for your feedback, 
after our call we determined that the problem occurs when a field is accidentally added multiple times in one entry view. Mostly this happens when the default view is generated with every field in an instance and adds the subfield of a fieldgroup as well as the field itself.

We don't add fieldgroups to the defaults anymore, fix here:
https://github.com/michaelpollak/moodle-mod_datalynx/commit/92f5c010658008b48e5dd9eec3e12e856498a12f

We validate if fields are added more than once to an entry view.
https://github.com/michaelpollak/moodle-mod_datalynx/commit/2594f644ff791c4da5a2c3fb4c7f33e5e2806257
https://github.com/michaelpollak/moodle-mod_datalynx/commit/2f08ed018b62dcfff76932183308e6d275b07c3b

If we add the same field with a special renderer or behaviour it does not work as expected, will update once fixed.

**Comment by dasistwas** [comment]
Works fine now. Thank you.
