### ISSUE TITLE
Custom Filter does not return any entry even if it should

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#62]
I tested the custom filter with text fields (autocomplete), teammemberselect and files, but there was always no result returned even if the filter matched exactly an entry. Following filter settings:

![Screenshot_2019-06-29 Bericht hochladen Benutzerdefinierte Filter (Verwaltungsmodus)](https://user-images.githubusercontent.com/1620975/60374882-e2610080-9a06-11e9-9dfe-1c60e6608e79.png)

[datalynx-filter-problem-testing.zip](https://github.com/dasistwas/moodle-mod_datalynx/files/3341093/datalynx-filter-problem-testing.zip)

Please rename zip to mbz in order to test.

**Comment by michaelpollak** [comment]
I've tested this and can reproduce, seems like a combined issue that shows up with this complex customfilter.

1) Customfilter of files defaults to "missing" even if nothing is set. This is not ignored and thus we have to set files to "existing" or all entries with uploaded files are dropped from the search query. I don't think this is expected behaviour and if nothing is set file status should not be evaluated.

2) Customfilter of radiobutton fails when nothing is set. It resolves to "ANY_OF 0" which usually is not a valid search. I propose catching this and rewriting "ANY_OF 0" to "NOT 0", testing patch right now.

**Comment by michaelpollak** [comment]
Fixed radiobuttons in the select renderer, after testing the other approach which would've made it impossible to use 0 as a valid select value.

**Comment by michaelpollak** [comment]
Testing worked fine, we will need to check all other field types as well. I'll work on that tomorrow and post updates here. Thanks.

**Comment by dasistwas** [comment]
thank you, works now.
