### ISSUE TITLE
When teammemberselect ist required in fieldgroup, validation fails

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#79]
The problem is, that you have to fill out a team member for all of the the repeated fields, not only for the first one. So the hidden fields also show error:

>  You must select at least 1 team members!

**Comment by michaelpollak** [comment]
There are multiple ways to set a field within a fieldgroup as required. I am currently testing:
Set "min teamsize" in teammemverselect field to > 1

This causes all fields to be evaluated because all fields have to be passed on after the validation process. I am not sure how to pass data from hidden fields to the update process but ignore the required status in the process, working on this now.

I feel like this is a duplicate of #60?

**Comment by dasistwas** [comment]
Copied from #60 and closing the other issue.
When not all available rows/lines of the fieldgroup are filled out with at least one teammember, then the form can not be saved. Because there is a check of the hidden fields server side.

**Comment by michaelpollak** [comment]
Passed information about last visible line of fieldgroup to the validation, this allows the validation to be skipped for teammember select fields that are not visible. 
Quite a bit of overhead but I was not able to find any other solution. Will test a little more but at the moment this looks sturdy.

**Comment by dasistwas** [comment]
Great. Looks good. Just works as it should. Thank you for bringing up that solution.
